### ISSUE TITLE
数据增强导致prompt的groudtruth出错

### ISSUE THREAD

**Issue by lavainhat** [windygoo/PromptNucSeg#8]
在重现pannuke训练prompter的过程中，出现了以下错误：
Traceback (most recent call last):
  File "/mnt/s1/yj/code/PromptNucSeg/prompter/main.py", line 254, in <module>
    main()
  File "/mnt/s1/yj/code/PromptNucSeg/prompter/main.py", line 179, in main
    log_info = train_one_epoch(
  File "/mnt/s1/yj/code/PromptNucSeg/prompter/engine.py", line 32, in train_one_epoch
    for data_iter_step, (images, masks, points_list, labels_list,img_path) in enumerate(
  File "/mnt/s1/yj/code/PromptNucSeg/prompter/utils.py", line 131, in log_every
    for obj in iterable:
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/s1/yj/anaconda3/envs/diff/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/s1/yj/code/PromptNucSeg/prompter/dataset.py", line 126, in __getitem__
    return img, torch.cat(res[1:-1]), torch.cat(labels), mask, torch.as_tensor(ori_shape),img_path
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2 but got size 4 for tensor number 2 in the list.
我查看了数据变化过程，发现是数据增强时导致原来的GTpoint的shape发生了变化导致的，是否是pannuke的config文件有错？还是说需要额外的处理？

**Comment by lavainhat** [comment]
ShiftScaleRotate这种数据增强方法是直接问题发生的原因，在注释掉这种方法后问题不再发生

**Comment by windygoo** [comment]
> ShiftScaleRotate这种数据增强方法是直接问题发生的原因，在注释掉这种方法后问题不再发生

我记得这个数据增强好像还挺有用的。

是训练一开始就报错，还是在中间某个iter报错的

**Comment by lavainhat** [comment]
> > ShiftScaleRotate这种数据增强方法是直接问题发生的原因，在注释掉这种方法后问题不再发生
> 
> 我记得这个数据增强好像还挺有用的。
> 
> 是训练一开始就报错，还是在中间某个iter报错的
大部分都会报错，试了几次，基本前十个就会报错

**Comment by windygoo** [comment]
> 大部分都会报错，试了几次，基本前十个就会报错

是不是数据预处理没做对

**Comment by windygoo** [comment]
> 大部分都会报错，试了几次，基本前十个就会报错

可以加我微信 18957154658 交流一下
